[tool.poetry]
name = "lstm_chem"
version = "0.2.1"
description = "Implementation of the paper - Generative Recurrent Networks for De Novo Drug Design."
authors = ["topazape <topazape@gmail.com>"]
license = "The Unlicense"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.1"
tqdm = "^4.43.0"
bunch = "^1.0.1"
matplotlib = "^3.2.1"
scikit-learn = "^0.22.2"
tensorflow = "2.1.0"
tensorflow-estimator = "2.1.0"
pillow = "^7.0.0"

[tool.poetry.dev-dependencies]
python-language-server = {extras = ["yapf"], version = "^0.31.8"}
jupyter = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
